<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.bundle_winsqlite3" Version="2.1.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Anamnesis.Application\Anamnesis.Application.csproj" />
  </ItemGroup>
</Project>
